/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/admin` | `/admin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/admin/inspectors` | `/admin/inspectors`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/admin/seizures` | `/admin/seizures`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/admin/slaughterhouses` | `/admin/slaughterhouses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/inspector` | `/inspector`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/inspector/new` | `/inspector/new`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/admin` | `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/admin/inspectors` | `/admin/inspectors`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/admin/seizures` | `/admin/seizures`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/admin/slaughterhouses` | `/admin/slaughterhouses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/inspector` | `/inspector`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/inspector/new` | `/inspector/new`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/admin${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/admin/inspectors${`?${string}` | `#${string}` | ''}` | `/admin/inspectors${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/admin/seizures${`?${string}` | `#${string}` | ''}` | `/admin/seizures${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/admin/slaughterhouses${`?${string}` | `#${string}` | ''}` | `/admin/slaughterhouses${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/inspector${`?${string}` | `#${string}` | ''}` | `/inspector${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/inspector/new${`?${string}` | `#${string}` | ''}` | `/inspector/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/admin` | `/admin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/admin/inspectors` | `/admin/inspectors`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/admin/seizures` | `/admin/seizures`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/admin/slaughterhouses` | `/admin/slaughterhouses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/inspector` | `/inspector`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/inspector/new` | `/inspector/new`; params?: Router.UnknownInputParams; };
    }
  }
}
